# Generated by Django 3.1 on 2020-08-04 11:11

from django.db import migrations


def forwards_func(apps, schema_editor):
    Category = apps.get_model("myapp", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).bulk_create([
      Category(name=f"cat-{n}") for n in range(1000)
    ])


def reverse_func(apps, schema_editor):
    Category = apps.get_model("myapp", "Category")
    db_alias = schema_editor.connection.alias
    Category.objects.using(db_alias).filter(name__startswith="cat-").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(forwards_func, reverse_func)    
    ]
